//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_compra
    {
        public c_compra()
        {
            this.c_dtl_compra_detalle = new HashSet<c_dtl_compra_detalle>();
        }
    
        public int c_id { get; set; }
        public int c_id_i { get; set; }
        public System.DateTime c_fecha { get; set; }
        public string c_codigoFactura { get; set; }
        public string c_descripcion { get; set; }
        public Nullable<int> c_id_usuarioCreacion { get; set; }
        public Nullable<int> c_id_ope { get; set; }
    
        public virtual i_inventario i_inventario { get; set; }
        public virtual ope_operacion ope_operacion { get; set; }
        public virtual ICollection<c_dtl_compra_detalle> c_dtl_compra_detalle { get; set; }
    }
}
