//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_dtl_compra_detalle
    {
        public int c_dtl_id { get; set; }
        public int c_dtl_id_c { get; set; }
        public int c_dtl_id_mp { get; set; }
        public double c_dtl_cantidad { get; set; }
    
        public virtual c_compra c_compra { get; set; }
        public virtual mp_materiaPrima mp_materiaPrima { get; set; }
    }
}
