//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class carg_cargoInventario
    {
        public int carg_id { get; set; }
        public int carg_id_ope { get; set; }
        public Nullable<int> carg_id_i { get; set; }
        public Nullable<int> carg_id_mp { get; set; }
        public Nullable<double> carg_cantidad { get; set; }
        public Nullable<int> carg_id_usuarioCreacion { get; set; }
    
        public virtual i_inventario i_inventario { get; set; }
        public virtual ope_operacion ope_operacion { get; set; }
    }
}
