//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ce_comidaEmpleado
    {
        public ce_comidaEmpleado()
        {
            this.ce_dtl_comidaEmpleado_detalle = new HashSet<ce_dtl_comidaEmpleado_detalle>();
        }
    
        public int ce_id { get; set; }
        public System.DateTime ce_fecha { get; set; }
        public int ce_cantidadEmpleados { get; set; }
        public string ce_descripcion { get; set; }
        public int ce_id_i { get; set; }
        public Nullable<int> ce_id_usuarioCreacion { get; set; }
        public Nullable<int> ce_id_ope { get; set; }
    
        public virtual i_inventario i_inventario { get; set; }
        public virtual ope_operacion ope_operacion { get; set; }
        public virtual ICollection<ce_dtl_comidaEmpleado_detalle> ce_dtl_comidaEmpleado_detalle { get; set; }
    }
}
