//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ce_dtl_comidaEmpleado_detalle
    {
        public int ce_dtl_id { get; set; }
        public int ce_dtl_id_ce { get; set; }
        public int ce_dtl_id_p { get; set; }
        public double ce_dtl_cantidad { get; set; }
    
        public virtual ce_comidaEmpleado ce_comidaEmpleado { get; set; }
        public virtual p_producto p_producto { get; set; }
    }
}
