//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ce_dtl_comidaEmpleado_detalle
    {
        public int ce_dtl_id { get; set; }
        public int ce_dtl_id_ce { get; set; }
        public int ce_dtl_id_p { get; set; }
        public double ce_dtl_cantidad { get; set; }
    
        public virtual ce_comidaEmpleado ce_comidaEmpleado { get; set; }
        public virtual p_producto p_producto { get; set; }
    }
}
