//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class dc_desechoCompleto
    {
        public int dc_id { get; set; }
        public int dc_id_d { get; set; }
        public int dc_id_p { get; set; }
        public int dc_cantidad { get; set; }
    
        public virtual d_desecho d_desecho { get; set; }
        public virtual p_producto p_producto { get; set; }
    }
}
