//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class dc_desechoCompleto
    {
        public int dc_id { get; set; }
        public int dc_id_d { get; set; }
        public int dc_id_p { get; set; }
        public int dc_cantidad { get; set; }
    
        public virtual d_desecho d_desecho { get; set; }
        public virtual p_producto p_producto { get; set; }
    }
}
