//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class deg_dtl_degustacion_detalle
    {
        public int deg_dtl_id { get; set; }
        public int deg_dtl_id_deg { get; set; }
        public int deg_dtl_id_p { get; set; }
        public int deg_dtl_cantidad { get; set; }
    
        public virtual deg_degustacion deg_degustacion { get; set; }
        public virtual p_producto p_producto { get; set; }
    }
}
