//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class deg_degustacion
    {
        public deg_degustacion()
        {
            this.deg_dtl_degustacion_detalle = new HashSet<deg_dtl_degustacion_detalle>();
        }
    
        public int deg_id { get; set; }
        public int deg_id_i { get; set; }
        public System.DateTime deg_fecha { get; set; }
        public string deg_descripcion { get; set; }
        public Nullable<int> deg_id_usuarioCreacion { get; set; }
        public Nullable<int> deg_id_ope { get; set; }
    
        public virtual i_inventario i_inventario { get; set; }
        public virtual ope_operacion ope_operacion { get; set; }
        public virtual ICollection<deg_dtl_degustacion_detalle> deg_dtl_degustacion_detalle { get; set; }
    }
}
