//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class deg_dtl_degustacion_detalle
    {
        public int deg_dtl_id { get; set; }
        public int deg_dtl_id_deg { get; set; }
        public int deg_dtl_id_p { get; set; }
        public int deg_dtl_cantidad { get; set; }
    
        public virtual deg_degustacion deg_degustacion { get; set; }
        public virtual p_producto p_producto { get; set; }
    }
}
