//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class desc_descargoInventario
    {
        public int desc_id { get; set; }
        public int desc_id_ope { get; set; }
        public int desc_id_i { get; set; }
        public Nullable<int> desc_id_mp { get; set; }
        public Nullable<double> desc_cantidad { get; set; }
        public Nullable<System.DateTime> desc_fecha { get; set; }
        public Nullable<int> desc_id_usuarioCreacion { get; set; }
    
        public virtual i_inventario i_inventario { get; set; }
        public virtual ope_operacion ope_operacion { get; set; }
    }
}
