//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class di_desechoIncompleto
    {
        public int di_id { get; set; }
        public int di_id_d { get; set; }
        public int di_id_mp { get; set; }
        public double di_cantidad { get; set; }
    
        public virtual d_desecho d_desecho { get; set; }
    }
}
