//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ii_inventarioInterno
    {
        public int ii_id { get; set; }
        public int ii_id_i { get; set; }
        public int ii_id_mp { get; set; }
        public string ii_mp_descripcion { get; set; }
        public Nullable<double> ii_existencia { get; set; }
        public Nullable<bool> ii_activo { get; set; }
    
        public virtual i_inventario i_inventario { get; set; }
    }
}
