//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ii_inventarioInterno
    {
        public int ii_id { get; set; }
        public int ii_id_i { get; set; }
        public int ii_id_mp { get; set; }
        public string ii_mp_descripcion { get; set; }
        public Nullable<double> ii_existencia { get; set; }
        public Nullable<bool> ii_activo { get; set; }
    
        public virtual i_inventario i_inventario { get; set; }
    }
}
