//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mp_materiaPrima
    {
        public mp_materiaPrima()
        {
            this.c_dtl_compra_detalle = new HashSet<c_dtl_compra_detalle>();
            this.r_dtl_recetaDetalle = new HashSet<r_dtl_recetaDetalle>();
            this.te_transferenciaEntrada = new HashSet<te_transferenciaEntrada>();
            this.ts_transferenciaSalida = new HashSet<ts_transferenciaSalida>();
        }
    
        public int mp_id { get; set; }
        public string mp_codigo { get; set; }
        public string mp_nombre { get; set; }
        public string mp_unidadMedida { get; set; }
        public Nullable<double> mp_cantidadMinima { get; set; }
        public Nullable<bool> mp_estado { get; set; }
    
        public virtual ICollection<c_dtl_compra_detalle> c_dtl_compra_detalle { get; set; }
        public virtual ICollection<r_dtl_recetaDetalle> r_dtl_recetaDetalle { get; set; }
        public virtual ICollection<te_transferenciaEntrada> te_transferenciaEntrada { get; set; }
        public virtual ICollection<ts_transferenciaSalida> ts_transferenciaSalida { get; set; }
    }
}
