//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_producto
    {
        public p_producto()
        {
            this.ce_dtl_comidaEmpleado_detalle = new HashSet<ce_dtl_comidaEmpleado_detalle>();
            this.dc_desechoCompleto = new HashSet<dc_desechoCompleto>();
            this.deg_dtl_degustacion_detalle = new HashSet<deg_dtl_degustacion_detalle>();
            this.pc_productoCombo = new HashSet<pc_productoCombo>();
            this.pmx_dtl_productMix_detalle = new HashSet<pmx_dtl_productMix_detalle>();
            this.ps_productoSimple = new HashSet<ps_productoSimple>();
        }
    
        public int p_id { get; set; }
        public int p_id_r { get; set; }
        public string p_nombre { get; set; }
        public double p_precio { get; set; }
        public Nullable<int> p_tipo { get; set; }
    
        public virtual ICollection<ce_dtl_comidaEmpleado_detalle> ce_dtl_comidaEmpleado_detalle { get; set; }
        public virtual ICollection<dc_desechoCompleto> dc_desechoCompleto { get; set; }
        public virtual ICollection<deg_dtl_degustacion_detalle> deg_dtl_degustacion_detalle { get; set; }
        public virtual r_receta r_receta { get; set; }
        public virtual ICollection<pc_productoCombo> pc_productoCombo { get; set; }
        public virtual ICollection<pmx_dtl_productMix_detalle> pmx_dtl_productMix_detalle { get; set; }
        public virtual ICollection<ps_productoSimple> ps_productoSimple { get; set; }
    }
}
