//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pant_pantallas
    {
        public pant_pantallas()
        {
            this.per_premisosXrol = new HashSet<per_premisosXrol>();
        }
    
        public string pant_id { get; set; }
        public string pant_descripcion { get; set; }
    
        public virtual ICollection<per_premisosXrol> per_premisosXrol { get; set; }
    }
}
