//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pc_productoCombo
    {
        public int pc_id { get; set; }
        public int pc_id_p { get; set; }
        public int pc_id_pc_ps { get; set; }
        public string pc_cantidad_ps { get; set; }
    
        public virtual p_producto p_producto { get; set; }
        public virtual ps_productoSimple ps_productoSimple { get; set; }
    }
}
