//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pc_productoCombo
    {
        public int pc_id { get; set; }
        public int pc_id_p { get; set; }
        public int pc_id_pc_ps { get; set; }
        public string pc_cantidad_ps { get; set; }
    
        public virtual p_producto p_producto { get; set; }
        public virtual ps_productoSimple ps_productoSimple { get; set; }
    }
}
