//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class per_premisosXrol
    {
        public int pxr_id { get; set; }
        public string pxrl_id_pant { get; set; }
        public Nullable<int> pxr_id_rol { get; set; }
        public Nullable<int> pxr_id_user { get; set; }
    
        public virtual pant_pantallas pant_pantallas { get; set; }
        public virtual rol_roles rol_roles { get; set; }
        public virtual usr_usuarios usr_usuarios { get; set; }
    }
}
