//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pmx_dtl_productMix_detalle
    {
        public int pmx_dtl_id { get; set; }
        public int pmx_dtl_id_pmx { get; set; }
        public int pmx_dtl_cantidad { get; set; }
        public int pmx_dtl_id_p { get; set; }
    
        public virtual p_producto p_producto { get; set; }
        public virtual pmx_productMix pmx_productMix { get; set; }
    }
}
