//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pmx_productMix
    {
        public pmx_productMix()
        {
            this.pmx_dtl_productMix_detalle = new HashSet<pmx_dtl_productMix_detalle>();
        }
    
        public int pmx_id { get; set; }
        public int pmx_id_i { get; set; }
        public int pmx_id_pmx_dtl { get; set; }
        public System.DateTime pmx_fecha { get; set; }
        public string pmx_id_usuarioCreacion { get; set; }
        public Nullable<int> pmx_id_ope { get; set; }
    
        public virtual i_inventario i_inventario { get; set; }
        public virtual ope_operacion ope_operacion { get; set; }
        public virtual ICollection<pmx_dtl_productMix_detalle> pmx_dtl_productMix_detalle { get; set; }
    }
}
