//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pmx_dtl_productMix_detalle
    {
        public int pmx_dtl_id { get; set; }
        public int pmx_dtl_id_pmx { get; set; }
        public int pmx_dtl_cantidad { get; set; }
        public int pmx_dtl_id_p { get; set; }
    
        public virtual p_producto p_producto { get; set; }
        public virtual pmx_productMix pmx_productMix { get; set; }
    }
}
