//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class r_dtl_recetaDetalle
    {
        public int r_dtl_id { get; set; }
        public int r_dtl_id_r { get; set; }
        public int r_dtl_id_mp { get; set; }
        public double r_dtl_cantidad_mp { get; set; }
    
        public virtual mp_materiaPrima mp_materiaPrima { get; set; }
        public virtual r_receta r_receta { get; set; }
    }
}
