//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class r_dtl_recetaDetalle
    {
        public int r_dtl_id { get; set; }
        public int r_dtl_id_r { get; set; }
        public int r_dtl_id_mp { get; set; }
        public double r_dtl_cantidad_mp { get; set; }
    
        public virtual mp_materiaPrima mp_materiaPrima { get; set; }
        public virtual r_receta r_receta { get; set; }
    }
}
