//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class rol_roles
    {
        public rol_roles()
        {
            this.per_premisosXrol = new HashSet<per_premisosXrol>();
            this.usr_usuarios = new HashSet<usr_usuarios>();
        }
    
        public int rol_id { get; set; }
        public string rol_descripcion { get; set; }
    
        public virtual ICollection<per_premisosXrol> per_premisosXrol { get; set; }
        public virtual ICollection<usr_usuarios> usr_usuarios { get; set; }
    }
}
