//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SCIR_SistemaInventarioEntities : DbContext
    {
        public SCIR_SistemaInventarioEntities()
            : base("name=SCIR_SistemaInventarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<c_compra> c_compra { get; set; }
        public DbSet<c_dtl_compra_detalle> c_dtl_compra_detalle { get; set; }
        public DbSet<carg_cargoInventario> carg_cargoInventario { get; set; }
        public DbSet<ce_comidaEmpleado> ce_comidaEmpleado { get; set; }
        public DbSet<ce_dtl_comidaEmpleado_detalle> ce_dtl_comidaEmpleado_detalle { get; set; }
        public DbSet<d_desecho> d_desecho { get; set; }
        public DbSet<dc_desechoCompleto> dc_desechoCompleto { get; set; }
        public DbSet<deg_degustacion> deg_degustacion { get; set; }
        public DbSet<deg_dtl_degustacion_detalle> deg_dtl_degustacion_detalle { get; set; }
        public DbSet<desc_descargoInventario> desc_descargoInventario { get; set; }
        public DbSet<di_desechoIncompleto> di_desechoIncompleto { get; set; }
        public DbSet<i_inventario> i_inventario { get; set; }
        public DbSet<ii_inventarioInterno> ii_inventarioInterno { get; set; }
        public DbSet<ir_inventarioReal> ir_inventarioReal { get; set; }
        public DbSet<mp_materiaPrima> mp_materiaPrima { get; set; }
        public DbSet<ope_operacion> ope_operacion { get; set; }
        public DbSet<p_producto> p_producto { get; set; }
        public DbSet<pant_pantallas> pant_pantallas { get; set; }
        public DbSet<pc_productoCombo> pc_productoCombo { get; set; }
        public DbSet<per_premisosXrol> per_premisosXrol { get; set; }
        public DbSet<pmx_dtl_productMix_detalle> pmx_dtl_productMix_detalle { get; set; }
        public DbSet<pmx_productMix> pmx_productMix { get; set; }
        public DbSet<ps_productoSimple> ps_productoSimple { get; set; }
        public DbSet<r_dtl_recetaDetalle> r_dtl_recetaDetalle { get; set; }
        public DbSet<r_receta> r_receta { get; set; }
        public DbSet<rol_roles> rol_roles { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<t_transferencia> t_transferencia { get; set; }
        public DbSet<te_transferenciaEntrada> te_transferenciaEntrada { get; set; }
        public DbSet<tid_tipoDesecho> tid_tipoDesecho { get; set; }
        public DbSet<tir_tipoReceta> tir_tipoReceta { get; set; }
        public DbSet<tope_tipoOperacion> tope_tipoOperacion { get; set; }
        public DbSet<ts_transferenciaSalida> ts_transferenciaSalida { get; set; }
        public DbSet<usr_usuarios> usr_usuarios { get; set; }
        public DbSet<vin_variacionInventario> vin_variacionInventario { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_Login_Result> sp_Login(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Login_Result>("sp_Login", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_LoginPermisosXRol_Result> sp_LoginPermisosXRol(Nullable<int> id_rol)
        {
            var id_rolParameter = id_rol.HasValue ?
                new ObjectParameter("id_rol", id_rol) :
                new ObjectParameter("id_rol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LoginPermisosXRol_Result>("sp_LoginPermisosXRol", id_rolParameter);
        }
    
        public virtual int sp_mp_insert_NuevaMateriaPrima(string mp_codigo, string mp_nombre, string mp_unidadMedida, Nullable<double> mp_cantidadMinima, Nullable<bool> mp_estado)
        {
            var mp_codigoParameter = mp_codigo != null ?
                new ObjectParameter("mp_codigo", mp_codigo) :
                new ObjectParameter("mp_codigo", typeof(string));
    
            var mp_nombreParameter = mp_nombre != null ?
                new ObjectParameter("mp_nombre", mp_nombre) :
                new ObjectParameter("mp_nombre", typeof(string));
    
            var mp_unidadMedidaParameter = mp_unidadMedida != null ?
                new ObjectParameter("mp_unidadMedida", mp_unidadMedida) :
                new ObjectParameter("mp_unidadMedida", typeof(string));
    
            var mp_cantidadMinimaParameter = mp_cantidadMinima.HasValue ?
                new ObjectParameter("mp_cantidadMinima", mp_cantidadMinima) :
                new ObjectParameter("mp_cantidadMinima", typeof(double));
    
            var mp_estadoParameter = mp_estado.HasValue ?
                new ObjectParameter("mp_estado", mp_estado) :
                new ObjectParameter("mp_estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mp_insert_NuevaMateriaPrima", mp_codigoParameter, mp_nombreParameter, mp_unidadMedidaParameter, mp_cantidadMinimaParameter, mp_estadoParameter);
        }
    
        public virtual ObjectResult<sp_mp_select_all_Result> sp_mp_select_all()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mp_select_all_Result>("sp_mp_select_all");
        }
    
        public virtual ObjectResult<sp_mp_select_where_MateriaPrimaPorID_Result> sp_mp_select_where_MateriaPrimaPorID(Nullable<int> mp_id)
        {
            var mp_idParameter = mp_id.HasValue ?
                new ObjectParameter("mp_id", mp_id) :
                new ObjectParameter("mp_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mp_select_where_MateriaPrimaPorID_Result>("sp_mp_select_where_MateriaPrimaPorID", mp_idParameter);
        }
    
        public virtual ObjectResult<sp_mp_select_where_MateriaPrimaPorNombre_Result> sp_mp_select_where_MateriaPrimaPorNombre(string mp_nombre)
        {
            var mp_nombreParameter = mp_nombre != null ?
                new ObjectParameter("mp_nombre", mp_nombre) :
                new ObjectParameter("mp_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mp_select_where_MateriaPrimaPorNombre_Result>("sp_mp_select_where_MateriaPrimaPorNombre", mp_nombreParameter);
        }
    
        public virtual int sp_mp_update_MateriaPrima(Nullable<int> mp_id, Nullable<int> mp_codigo, string mp_nombre, string mp_unidadMedida, Nullable<double> mp_cantidadMinima, Nullable<bool> mp_estado)
        {
            var mp_idParameter = mp_id.HasValue ?
                new ObjectParameter("mp_id", mp_id) :
                new ObjectParameter("mp_id", typeof(int));
    
            var mp_codigoParameter = mp_codigo.HasValue ?
                new ObjectParameter("mp_codigo", mp_codigo) :
                new ObjectParameter("mp_codigo", typeof(int));
    
            var mp_nombreParameter = mp_nombre != null ?
                new ObjectParameter("mp_nombre", mp_nombre) :
                new ObjectParameter("mp_nombre", typeof(string));
    
            var mp_unidadMedidaParameter = mp_unidadMedida != null ?
                new ObjectParameter("mp_unidadMedida", mp_unidadMedida) :
                new ObjectParameter("mp_unidadMedida", typeof(string));
    
            var mp_cantidadMinimaParameter = mp_cantidadMinima.HasValue ?
                new ObjectParameter("mp_cantidadMinima", mp_cantidadMinima) :
                new ObjectParameter("mp_cantidadMinima", typeof(double));
    
            var mp_estadoParameter = mp_estado.HasValue ?
                new ObjectParameter("mp_estado", mp_estado) :
                new ObjectParameter("mp_estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mp_update_MateriaPrima", mp_idParameter, mp_codigoParameter, mp_nombreParameter, mp_unidadMedidaParameter, mp_cantidadMinimaParameter, mp_estadoParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<sp_t_select_fecha_Result> sp_t_select_fecha(Nullable<System.DateTime> t_fecha1, Nullable<System.DateTime> t_fecha2)
        {
            var t_fecha1Parameter = t_fecha1.HasValue ?
                new ObjectParameter("t_fecha1", t_fecha1) :
                new ObjectParameter("t_fecha1", typeof(System.DateTime));
    
            var t_fecha2Parameter = t_fecha2.HasValue ?
                new ObjectParameter("t_fecha2", t_fecha2) :
                new ObjectParameter("t_fecha2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_t_select_fecha_Result>("sp_t_select_fecha", t_fecha1Parameter, t_fecha2Parameter);
        }
    
        public virtual ObjectResult<sp_t_select_where_TransferenciaID_Result> sp_t_select_where_TransferenciaID(Nullable<int> t_id)
        {
            var t_idParameter = t_id.HasValue ?
                new ObjectParameter("t_id", t_id) :
                new ObjectParameter("t_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_t_select_where_TransferenciaID_Result>("sp_t_select_where_TransferenciaID", t_idParameter);
        }
    
        public virtual int sp_trans_delete_TransferenciaEntradaSalida(Nullable<int> t_id, Nullable<int> t_tipo)
        {
            var t_idParameter = t_id.HasValue ?
                new ObjectParameter("t_id", t_id) :
                new ObjectParameter("t_id", typeof(int));
    
            var t_tipoParameter = t_tipo.HasValue ?
                new ObjectParameter("t_tipo", t_tipo) :
                new ObjectParameter("t_tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_trans_delete_TransferenciaEntradaSalida", t_idParameter, t_tipoParameter);
        }
    
        public virtual int sp_trans_insert_NuevaTransferencia(Nullable<int> id, Nullable<int> t_id_i, Nullable<System.DateTime> t_fecha, string t_descripcion, Nullable<int> t_tipo, Nullable<int> t_id_usuarioCreacion, Nullable<int> t_id_ope)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var t_id_iParameter = t_id_i.HasValue ?
                new ObjectParameter("t_id_i", t_id_i) :
                new ObjectParameter("t_id_i", typeof(int));
    
            var t_fechaParameter = t_fecha.HasValue ?
                new ObjectParameter("t_fecha", t_fecha) :
                new ObjectParameter("t_fecha", typeof(System.DateTime));
    
            var t_descripcionParameter = t_descripcion != null ?
                new ObjectParameter("t_descripcion", t_descripcion) :
                new ObjectParameter("t_descripcion", typeof(string));
    
            var t_tipoParameter = t_tipo.HasValue ?
                new ObjectParameter("t_tipo", t_tipo) :
                new ObjectParameter("t_tipo", typeof(int));
    
            var t_id_usuarioCreacionParameter = t_id_usuarioCreacion.HasValue ?
                new ObjectParameter("t_id_usuarioCreacion", t_id_usuarioCreacion) :
                new ObjectParameter("t_id_usuarioCreacion", typeof(int));
    
            var t_id_opeParameter = t_id_ope.HasValue ?
                new ObjectParameter("t_id_ope", t_id_ope) :
                new ObjectParameter("t_id_ope", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_trans_insert_NuevaTransferencia", idParameter, t_id_iParameter, t_fechaParameter, t_descripcionParameter, t_tipoParameter, t_id_usuarioCreacionParameter, t_id_opeParameter);
        }
    
        public virtual int sp_trans_insert_TransferenciaEntradas(Nullable<int> te_id, Nullable<int> te_id_t, Nullable<int> te_mp_id, Nullable<double> te_cantidad)
        {
            var te_idParameter = te_id.HasValue ?
                new ObjectParameter("te_id", te_id) :
                new ObjectParameter("te_id", typeof(int));
    
            var te_id_tParameter = te_id_t.HasValue ?
                new ObjectParameter("te_id_t", te_id_t) :
                new ObjectParameter("te_id_t", typeof(int));
    
            var te_mp_idParameter = te_mp_id.HasValue ?
                new ObjectParameter("te_mp_id", te_mp_id) :
                new ObjectParameter("te_mp_id", typeof(int));
    
            var te_cantidadParameter = te_cantidad.HasValue ?
                new ObjectParameter("te_cantidad", te_cantidad) :
                new ObjectParameter("te_cantidad", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_trans_insert_TransferenciaEntradas", te_idParameter, te_id_tParameter, te_mp_idParameter, te_cantidadParameter);
        }
    
        public virtual int sp_trans_insert_TransferenciaEntradas1(Nullable<int> te_id, Nullable<int> te_id_t, Nullable<int> te_mp_id, Nullable<double> te_cantidad)
        {
            var te_idParameter = te_id.HasValue ?
                new ObjectParameter("te_id", te_id) :
                new ObjectParameter("te_id", typeof(int));
    
            var te_id_tParameter = te_id_t.HasValue ?
                new ObjectParameter("te_id_t", te_id_t) :
                new ObjectParameter("te_id_t", typeof(int));
    
            var te_mp_idParameter = te_mp_id.HasValue ?
                new ObjectParameter("te_mp_id", te_mp_id) :
                new ObjectParameter("te_mp_id", typeof(int));
    
            var te_cantidadParameter = te_cantidad.HasValue ?
                new ObjectParameter("te_cantidad", te_cantidad) :
                new ObjectParameter("te_cantidad", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_trans_insert_TransferenciaEntradas1", te_idParameter, te_id_tParameter, te_mp_idParameter, te_cantidadParameter);
        }
    
        public virtual int sp_trans_insert_TransferenciaSalida(Nullable<int> t_id, Nullable<int> t_mp_id, Nullable<double> t_mp_cantidad)
        {
            var t_idParameter = t_id.HasValue ?
                new ObjectParameter("t_id", t_id) :
                new ObjectParameter("t_id", typeof(int));
    
            var t_mp_idParameter = t_mp_id.HasValue ?
                new ObjectParameter("t_mp_id", t_mp_id) :
                new ObjectParameter("t_mp_id", typeof(int));
    
            var t_mp_cantidadParameter = t_mp_cantidad.HasValue ?
                new ObjectParameter("t_mp_cantidad", t_mp_cantidad) :
                new ObjectParameter("t_mp_cantidad", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_trans_insert_TransferenciaSalida", t_idParameter, t_mp_idParameter, t_mp_cantidadParameter);
        }
    
        public virtual int sp_trans_insert_TransferenciaSalidas1(Nullable<int> ts_id, Nullable<int> ts_id_t, Nullable<int> ts_mp_id, Nullable<double> ts_cantidad)
        {
            var ts_idParameter = ts_id.HasValue ?
                new ObjectParameter("ts_id", ts_id) :
                new ObjectParameter("ts_id", typeof(int));
    
            var ts_id_tParameter = ts_id_t.HasValue ?
                new ObjectParameter("ts_id_t", ts_id_t) :
                new ObjectParameter("ts_id_t", typeof(int));
    
            var ts_mp_idParameter = ts_mp_id.HasValue ?
                new ObjectParameter("ts_mp_id", ts_mp_id) :
                new ObjectParameter("ts_mp_id", typeof(int));
    
            var ts_cantidadParameter = ts_cantidad.HasValue ?
                new ObjectParameter("ts_cantidad", ts_cantidad) :
                new ObjectParameter("ts_cantidad", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_trans_insert_TransferenciaSalidas1", ts_idParameter, ts_id_tParameter, ts_mp_idParameter, ts_cantidadParameter);
        }
    
        public virtual ObjectResult<sp_trans_select_all_EntradasSalidas_Result> sp_trans_select_all_EntradasSalidas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_trans_select_all_EntradasSalidas_Result>("sp_trans_select_all_EntradasSalidas");
        }
    
        public virtual ObjectResult<sp_trans_select_where_EntradasSalidas_Result> sp_trans_select_where_EntradasSalidas(Nullable<int> t_id, Nullable<int> t_tipo)
        {
            var t_idParameter = t_id.HasValue ?
                new ObjectParameter("t_id", t_id) :
                new ObjectParameter("t_id", typeof(int));
    
            var t_tipoParameter = t_tipo.HasValue ?
                new ObjectParameter("t_tipo", t_tipo) :
                new ObjectParameter("t_tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_trans_select_where_EntradasSalidas_Result>("sp_trans_select_where_EntradasSalidas", t_idParameter, t_tipoParameter);
        }
    
        public virtual int sp_trans_update_TransferenciaEntrada(Nullable<int> t_id, Nullable<int> t_mp_id, Nullable<double> t_mp_cantidad, Nullable<int> t_mp_idNuevo, Nullable<double> t_mp_cantidadNuevo)
        {
            var t_idParameter = t_id.HasValue ?
                new ObjectParameter("t_id", t_id) :
                new ObjectParameter("t_id", typeof(int));
    
            var t_mp_idParameter = t_mp_id.HasValue ?
                new ObjectParameter("t_mp_id", t_mp_id) :
                new ObjectParameter("t_mp_id", typeof(int));
    
            var t_mp_cantidadParameter = t_mp_cantidad.HasValue ?
                new ObjectParameter("t_mp_cantidad", t_mp_cantidad) :
                new ObjectParameter("t_mp_cantidad", typeof(double));
    
            var t_mp_idNuevoParameter = t_mp_idNuevo.HasValue ?
                new ObjectParameter("t_mp_idNuevo", t_mp_idNuevo) :
                new ObjectParameter("t_mp_idNuevo", typeof(int));
    
            var t_mp_cantidadNuevoParameter = t_mp_cantidadNuevo.HasValue ?
                new ObjectParameter("t_mp_cantidadNuevo", t_mp_cantidadNuevo) :
                new ObjectParameter("t_mp_cantidadNuevo", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_trans_update_TransferenciaEntrada", t_idParameter, t_mp_idParameter, t_mp_cantidadParameter, t_mp_idNuevoParameter, t_mp_cantidadNuevoParameter);
        }
    
        public virtual int sp_trans_update_TransferenciaSalida(Nullable<int> t_id, Nullable<int> t_mp_id, Nullable<double> t_mp_cantidad, Nullable<int> t_mp_idNuevo, Nullable<double> t_mp_cantidadNuevo)
        {
            var t_idParameter = t_id.HasValue ?
                new ObjectParameter("t_id", t_id) :
                new ObjectParameter("t_id", typeof(int));
    
            var t_mp_idParameter = t_mp_id.HasValue ?
                new ObjectParameter("t_mp_id", t_mp_id) :
                new ObjectParameter("t_mp_id", typeof(int));
    
            var t_mp_cantidadParameter = t_mp_cantidad.HasValue ?
                new ObjectParameter("t_mp_cantidad", t_mp_cantidad) :
                new ObjectParameter("t_mp_cantidad", typeof(double));
    
            var t_mp_idNuevoParameter = t_mp_idNuevo.HasValue ?
                new ObjectParameter("t_mp_idNuevo", t_mp_idNuevo) :
                new ObjectParameter("t_mp_idNuevo", typeof(int));
    
            var t_mp_cantidadNuevoParameter = t_mp_cantidadNuevo.HasValue ?
                new ObjectParameter("t_mp_cantidadNuevo", t_mp_cantidadNuevo) :
                new ObjectParameter("t_mp_cantidadNuevo", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_trans_update_TransferenciaSalida", t_idParameter, t_mp_idParameter, t_mp_cantidadParameter, t_mp_idNuevoParameter, t_mp_cantidadNuevoParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
