//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class te_transferenciaEntrada
    {
        public int te_id { get; set; }
        public int te_id_t { get; set; }
        public int te_id_mp { get; set; }
        public double te_cantidad { get; set; }
    
        public virtual mp_materiaPrima mp_materiaPrima { get; set; }
        public virtual t_transferencia t_transferencia { get; set; }
    }
}
