//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tir_tipoReceta
    {
        public tir_tipoReceta()
        {
            this.r_receta = new HashSet<r_receta>();
        }
    
        public int tir_id { get; set; }
        public string tir_descripcion { get; set; }
    
        public virtual ICollection<r_receta> r_receta { get; set; }
    }
}
