//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tir_tipoReceta
    {
        public tir_tipoReceta()
        {
            this.r_receta = new HashSet<r_receta>();
        }
    
        public int tir_id { get; set; }
        public string tir_descripcion { get; set; }
    
        public virtual ICollection<r_receta> r_receta { get; set; }
    }
}
