//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tope_tipoOperacion
    {
        public tope_tipoOperacion()
        {
            this.ope_operacion = new HashSet<ope_operacion>();
        }
    
        public int tope_id { get; set; }
        public string tope_descripcion { get; set; }
    
        public virtual ICollection<ope_operacion> ope_operacion { get; set; }
    }
}
