//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tope_tipoOperacion
    {
        public tope_tipoOperacion()
        {
            this.ope_operacion = new HashSet<ope_operacion>();
        }
    
        public int tope_id { get; set; }
        public string tope_descripcion { get; set; }
    
        public virtual ICollection<ope_operacion> ope_operacion { get; set; }
    }
}
