//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ts_transferenciaSalida
    {
        public int ts_id { get; set; }
        public int ts_id_t { get; set; }
        public int ts_id_mp { get; set; }
        public double ts_cantidad { get; set; }
    
        public virtual mp_materiaPrima mp_materiaPrima { get; set; }
        public virtual t_transferencia t_transferencia { get; set; }
    }
}
