//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class usr_usuarios
    {
        public usr_usuarios()
        {
            this.per_premisosXrol = new HashSet<per_premisosXrol>();
        }
    
        public int usr_id { get; set; }
        public string usr_nombre { get; set; }
        public string usr_password { get; set; }
        public int usr_id_rol { get; set; }
    
        public virtual ICollection<per_premisosXrol> per_premisosXrol { get; set; }
        public virtual rol_roles rol_roles { get; set; }
    }
}
