//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class usr_usuarios
    {
        public usr_usuarios()
        {
            this.per_premisosXrol = new HashSet<per_premisosXrol>();
        }
    
        public int usr_id { get; set; }
        public string usr_nombre { get; set; }
        public string usr_password { get; set; }
        public int usr_id_rol { get; set; }
    
        public virtual ICollection<per_premisosXrol> per_premisosXrol { get; set; }
        public virtual rol_roles rol_roles { get; set; }
    }
}
