//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vin_variacionInventario
    {
        public int vin_id { get; set; }
        public int vin_id_i { get; set; }
        public Nullable<int> vin_id_mp { get; set; }
        public string vin_mp_descripcion { get; set; }
        public Nullable<double> vin_existenciaReal { get; set; }
        public Nullable<double> vin_existenciaInterna { get; set; }
        public Nullable<double> vin_variacion { get; set; }
        public Nullable<int> vin_id_usuarioCreacion { get; set; }
    
        public virtual i_inventario i_inventario { get; set; }
    }
}
