//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeInventariosSCIR.BussinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vin_variacionInventario
    {
        public int vin_id { get; set; }
        public int vin_id_i { get; set; }
        public Nullable<int> vin_id_mp { get; set; }
        public string vin_mp_descripcion { get; set; }
        public Nullable<double> vin_existenciaReal { get; set; }
        public Nullable<double> vin_existenciaInterna { get; set; }
        public Nullable<double> vin_variacion { get; set; }
        public Nullable<int> vin_id_usuarioCreacion { get; set; }
    
        public virtual i_inventario i_inventario { get; set; }
    }
}
